// <auto-generated />
using System;
using Integracao.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integracao.Infra.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integracao.Domain.Entities.TDeParaStatus", b =>
                {
                    b.Property<long>("AcodStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_STATUS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcodStatus"));

                    b.Property<int>("AcodStatusDevops")
                        .HasColumnType("int")
                        .HasColumnName("ACOD_STATUS_DEVOPS");

                    b.Property<int>("AcodStatusGlpi")
                        .HasColumnType("int")
                        .HasColumnName("ACOD_STATUS_Glpi");

                    b.Property<string>("AdesStatusDevops")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ADES_STATUS_DEVOPS");

                    b.Property<string>("AdesStatusGlpi")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ADES_STATUS_GLPI");

                    b.HasKey("AcodStatus");

                    b.ToTable("TDE_PARA_STATUS", (string)null);
                });

            modelBuilder.Entity("Integracao.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("AcodTickets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_TICKET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcodTickets"));

                    b.Property<long>("AcodStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_STATUS");

                    b.Property<long>("AcodTicketsDevops")
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_TICKET_DEVOPS");

                    b.Property<long>("AcodTicketsglpi")
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_TICKET_GLPI");

                    b.Property<long>("AcodUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_USUARIO");

                    b.Property<DateTime>("AdatAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("ADAT_ALTERACAO");

                    b.HasKey("AcodTickets");

                    b.ToTable("TTICKETS", (string)null);
                });

            modelBuilder.Entity("Integracao.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("AcodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ACOD_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AcodUsuario"));

                    b.Property<string>("AdesEmail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ADES_EMAIL");

                    b.Property<string>("AdesUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ADES_USUARIO");

                    b.HasKey("AcodUsuario");

                    b.ToTable("TUSUARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
